Parameters:
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.180.0.0/16

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.180.8.0/21

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.180.16.0/21

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.180.24.0/21

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.180.32.0/21

  DBInstanceType:
    Description: Type of RDS instance to be used for the PostgreSQL instance.
    Type: String
    Default: db.t3.small

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/democracy-stack/aws/network-stack.yml
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
      Tags:
        - Key: Project
          Value: Democracy
        - Key: Environment
          Value: All
        - Key: Stack-Name
          Value: NetworkStack

  TestDataStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/democracy-stack/aws/data-stack.yml
      Parameters:
        EnvironmentName: test
        VPC: !GetAtt NetworkStack.Outputs.NetworkStack
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        DBSubnetGroup: !GetAtt NetworkStack.Outputs.DBSubnetGroup
        DBServerSecurityGroup: !GetAtt NetworkStack.Outputs.DBServerSecurityGroup
        EFSSecurityGroup: !GetAtt NetworkStack.Outputs.EFSSecurityGroup
        DBUsername: !GetAtt NetworkStack.Outputs.DBUsername
        DBPassword: !GetAtt NetworkStack.Outputs.DBPassword
        DBInstanceType: !Ref DBInstanceType
      Tags:
        - Key: Project
          Value: Democracy
        - Key: Environment
          Value: test
        - Key: Stack-Name
          Value: TestDataStack

  UATDataStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/democracy-stack/aws/data-stack.yml
      Parameters:
        EnvironmentName: uat
        VPC: !GetAtt NetworkStack.Outputs.NetworkStack
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        DBSubnetGroup: !GetAtt NetworkStack.Outputs.DBSubnetGroup
        DBServerSecurityGroup: !GetAtt NetworkStack.Outputs.DBServerSecurityGroup
        EFSSecurityGroup: !GetAtt NetworkStack.Outputs.EFSSecurityGroup
        DBUsername: !GetAtt NetworkStack.Outputs.DBUsername
        DBPassword: !GetAtt NetworkStack.Outputs.DBPassword
        DBInstanceType: !Ref DBInstanceType
      Tags:
        - Key: Project
          Value: Democracy
        - Key: Environment
          Value: uat
        - Key: Stack-Name
          Value: UATDataStack

  ProdDataStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/democracy-stack/aws/data-stack.yml
      Parameters:
        EnvironmentName: prod
        VPC: !GetAtt NetworkStack.Outputs.NetworkStack
        PrivateSubnet1: !GetAtt NetworkStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt NetworkStack.Outputs.PrivateSubnet2
        DBSubnetGroup: !GetAtt NetworkStack.Outputs.DBSubnetGroup
        DBServerSecurityGroup: !GetAtt NetworkStack.Outputs.DBServerSecurityGroup
        EFSSecurityGroup: !GetAtt NetworkStack.Outputs.EFSSecurityGroup
        DBUsername: !GetAtt NetworkStack.Outputs.DBUsername
        DBPassword: !GetAtt NetworkStack.Outputs.DBPassword
        DBInstanceType: !Ref DBInstanceType
      Tags:
        - Key: Project
          Value: Democracy
        - Key: Environment
          Value: prod
        - Key: Stack-Name
          Value: ProdDataStack

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !GetAtt NetworkStack.Outputs.VPC
  PrivateSubnet1:
    Description: A private subnets
    Value: !GetAtt NetworkStack.Outputs.PrivateSubnet1
  PrivateSubnet2:
    Description: A private subnets
    Value: !GetAtt NetworkStack.Outputs.PrivateSubnet2
  PublicSubnet1:
    Description: A public subnets
    Value: !GetAtt NetworkStack.Outputs.PublicSubnet1
  PublicSubnet2:
    Description: A public subnets
    Value: !GetAtt NetworkStack.Outputs.PublicSubnet2

  ECSHostSecurityGroup:
    Description: A reference to the security group for ECS hosts
    Value: !GetAtt NetworkStack.Outputs.ECSHostSecurityGroup
  LoadBalancerSecurityGroup:
    Description: A reference to the security group for load balancers
    Value: !GetAtt NetworkStack.Outputs.LoadBalancerSecurityGroup

  TestPostgresDatabaseEndpoint:
    Value: !GetAtt TestDataStack.Outputs.PostgresDatabaseEndpoint
  TestScraperEFSFileSystem:
    Value: !GetAtt TestDataStack.Outputs.ScraperEFSFileSystem

  UATPostgresDatabaseEndpoint:
    Value: !GetAtt UATDataStack.Outputs.PostgresDatabaseEndpoint
  UATScraperEFSFileSystem:
    Value: !GetAtt UATDataStack.Outputs.ScraperEFSFileSystem

  ProdPostgresDatabaseEndpoint:
    Value: !GetAtt ProdDataStack.Outputs.PostgresDatabaseEndpoint
  ProdScraperEFSFileSystem:
    Value: !GetAtt ProdDataStack.Outputs.ScraperEFSFileSystem
